[package]
name = "pom-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15.0"
pom-utils = { path = "../pom-utils" }

[dev-dependencies]
pom-utils = { path = "../pom-utils", features = ["snap"] }
