[package]
name = "pom"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
pom-lexer = { path = "../pom-lexer" }
pom-parser = { path = "../pom-parser" }
pom-sema = { path = "../pom-sema" }
serde = { version = "1.0.219", features = ["derive"] }
