[package]
name = "pom-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
pom-lexer = { path = "../pom-lexer" }
pom-utils = { path = "../pom-utils" }

[dev-dependencies]
pom-utils = { path = "../pom-utils", features = ["snap"] }
