name: CI

on:
  - push
  - pull_request

jobs:
  check:
    name: Check and Build Nix Flake (${{ matrix.system }})
    runs-on: ${{ matrix.runner_label }}

    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner_label: ubuntu-latest
          - system: aarch64-darwin
            runner_label: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v18
        with:
          determinate: true
          extra-conf: lazy-trees = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: wini
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check
        run: nix flake check -L --keep-going
