name: CI

on:
  - push
  - pull_request

jobs:
  check:
    name: Check and Build Nix Flake (${{ matrix.system }})
    runs-on: ${{ matrix.runner_label }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner_label: ubuntu-latest
          - system: aarch64-darwin
            runner_label: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.8.2

      - name: Check
        run: nix flake check -L --keep-going
